export * from './base.repository.js';
export * from './user.repository.js';
export * from './session.repository.js';
export * from './class.repository.js';
export * from './evaluation.repository.js';
export * from './question.repository.js';
export * from './student.repository.js';
export * from './studentCopy.repository.js';
export * from './answer.repository.js';
